steps:

  - commands: 
    - "yarn install"
    - "tsc --declaration false --noEmit"
    label: ":typescript:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn lint"
    label: ":eslint:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn test"
    label: ":jest:"

  - wait

  - commands: 
      - "yarn install"
      - "yarn build"
    label: ":rollup:"
