steps:
  - commands: 
    - "yarn install --ignore-scripts"
    - "yarn tsc --declaration false --noEmit"
    label: ":typescript:"

  - wait
  
  - commands: 
    - "yarn install --ignore-scripts"
    - "yarn lint"
    label: ":eslint:"

  - wait
  
  - commands: 
    - "yarn install --ignore-scripts"
    - "yarn test --collectCoverage"
    label: ":jest:"
    artifact_paths:
      - __artifacts__/*.pdf
      - coverage/*

  - wait

  - name: ":codeclimate:"
    plugins:
      - jobready/codeclimate-test-reporter#v2.0:
          artifact: "coverage/lcov.info"
          input_type: lcov
          prefix: '/var/lib/buildkite-agent/builds/enterprise-oss-bk-1/enterpriseoss/osso-react/'
  - wait

  - commands: 
      - "yarn install --ignore-scripts"
      - "yarn build"
    label: ":rollup:"
    
  - wait  

  - block: ":npm: Publish :red_button:"
    if: build.tag != null
  
  - name: "Push :npm:"
    commands: 
    - "yarn install --ignore-scripts"
    - "yarn build"
    - "npm publish"
    if: build.tag != null
