steps:
  - commands: 
    - "yarn install"
    - "yarn tsc --declaration false --noEmit"
    label: ":typescript:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn lint"
    label: ":eslint:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn test"
    label: ":jest:"
    artifact_paths:
      - __artifacts__/*.pdf

  - wait

  - commands: 
      - "yarn install"
      - "yarn build"
    label: ":rollup:"
