steps:
  - commands: 
    - "yarn install"
    - "yarn tsc --declaration false --noEmit"
    label: ":typescript:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn lint"
    label: ":eslint:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn test --collectCoverage"
    label: ":jest:"
    artifact_paths:
      - __artifacts__/*.pdf
      - coverage/*

  - wait

  - name: ":codeclimate: Report coverage"
    plugins:
      - jobready/codeclimate-test-reporter#v2.0:
          artifact: "coverage/clover.xml"
          input_type: lcov
          debug: true
          prefix: '/var/lib/buildkite-agent/builds/enterprise-oss-bk-1/enterpriseoss/osso-react/'
  - wait

  - commands: 
      - "yarn install"
      - "yarn build"
    label: ":rollup:"
